#!/bin/bash
clear
# This script automates the setup of Kali Linux as according to Tim
# Lansing's Kali Setup Lab for Net Attacks. The instructions have
# been cut down to omit some things to get up and running quick but this 
# could change.

# CHANGELOG
# 3/17/25 4:54PM: Completed first draft
# 3/17/25 6:32PM: Combined create_dirs with this script to make a cohesive
# all in one setup script.

# USAGE
# wget -qO- https://github.com/ToneBone54/congenial-palm-tree/raw/refs/heads/main/Scripts/Bash/KaliSetup | bash

# Update Kali
echo -e "Beginning updates...."
sleep 2
sudo apt-get update

# This command will only update currently installed packages. More work will be needed if we want to include dist/full-upgrade
# DEBIAN_FRONTEND is configured to prevent any input prompts from breaking the script flow
sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
sudo apt-get autoremove -y

# Install various tools
packages=("gobuster" "feroxbuster" "seclists" "evolution" "guestmount" "oscanner" "sipvicious" "redis-tools" "liblzf1" "crowbar" "html2text" "dirsearch" "kali-wallpapers-2023" "cifs-utils")
echo -e "\nInstalling ${packages[@]}..."
sleep 2
sudo apt-get install ${packages[@]} -y 

echo -e "\nVerifying packages..."
sleep 2

for pack in "${packages[@]}"; do
        if dpkg -l | grep -qw "$pack"; then
                echo "$pack found"
        else
                echo "$pack not found"
        fi
done

# Unzip rockyou
echo -e "\nUnzipping rockyou.txt..."
sudo gunzip /usr/share/wordlists/rockyou.txt.gz

#Begin personal directory creation
echo -e "\nChecking for practice directories..."

#Define variables for each dir
HTBdir=~/HTB
THMdir=~/THM
Sherlocks=~/HTB/Sherlocks
Chals=~/HTB/Challenges
vpnconfs=~/VPNConfigs
HTBconf=~/VPNConfigs/HTB
THMconf=~/VPNConfigs/THM

#Create directories
for dir in $HTBdir $THMdir $Sherlocks $Chals $vpnconfs $HTBconf $THMconf; do
        if [ -d $dir ]; then
                echo "$dir found!"
        else
                echo "$dir not found. Creating..."
                mkdir $dir
        fi
done
